### ISSUE TITLE
FeedBack

### ISSUE THREAD

**Issue by profxed** [jalalalwani/javascript2#1]
Hi @jalalalwani 
How are you, great job you did it right And i did learn some new tricks from your code kind of in the bonus question what i did is sort them and then remove the duplicated item from the array it's something fun to think about that for a while, but i didn't focus on how to remove the duplicated once without sorting the only thing you have is step 5 you didn't do it But i think it's okay because the solution is so easy
if don't mined i did copy your solution at the bonus step *With saving the owner content policy* :grin: 

And Good luck :+1:

**Comment by jalalalwani** [comment]
Sure @JawharBairakdar , this is the real perpose for doing the feedback , to learn from each other, about number 5 i done it first in the freecodecamp and then the webpage stuck in an infinitive loop 😂😂😂, but as you said it was easy, good luck and see you in hangout, don’t miss it.
